# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9e45d75887348d6f8145626444587617cb6039c379ab7c9a043bc6de3f207edcbae1b9485427d5b5ab6fc3997271ef304fe4a28ccb182d6705d6ef155a3a541

test:
  secret_key_base: 7b1c5a37ca25c0ac9ce0125c220a4182b006e9a0de04264908e3b9d010feca38c5c13927ad2792aaff05a9ccf2670a7500cf1e726eded0f128a9c703289642a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
